from manim import *
import numpy as np

class Test(Scene):
    def construct(self):
        axes = Axes(x_range=[-3, 3], y_range=[-3, 3],width=6,height=6, axis_config={"stroke_color": GREY,"include_numbers":True,"stroke_width":2})
        zerolabel = Text("0", font="SimSun", font_size=26).move_to(axes.c2p(-0.1,-0.2))
        self.play(FadeIn(axes), FadeIn(zerolabel))
        info3 = MathTex(r"\text{旋转矩阵:}A=\begin{bmatrix} \cos\alpha & -\sin\alpha \\ \sin\alpha & \cos\alpha \end{bmatrix}", font="SimSun", font_size=30).move_to(axes.c2p(-4.5,2))
        self.play(FadeIn(info3))
        info4 = MathTex(r"\text{作用于向量:}x=\begin{bmatrix} 2 \\ 1 \end{bmatrix}", font="SimSun", font_size=30, color=RED).next_to(info3, DOWN, aligned_edge=LEFT)
        self.play(FadeIn(info4))
        x = Arrow(axes.c2p(0,0), axes.c2p(2,1), buff=0, color=RED)
        self.play(Create(x))
        x_label = MathTex(r"x", font="SimSun", font_size=30, color=RED).move_to(axes.c2p(2.1,1.1))
        self.play(FadeIn(x_label))
        info5 = MathTex(r"A", font="SimSun", font_size=40, color=WHITE).next_to(info4, DOWN*2).shift(LEFT*0.5)
        info5_1 = MathTex(r"x", font="SimSun", font_size=40, color=RED).next_to(info5, RIGHT, buff=0.1).shift(DOWN*0.05)
        info5_2 = MathTex(r"=b", font="SimSun", font_size=40, color=BLUE).next_to(info5_1, RIGHT, buff=0.1).shift(UP*0.05)
        self.play(FadeIn(info5), FadeIn(info5_1), FadeIn(info5_2))
        sr1 = SurroundingRectangle(VGroup(info5, info5_1, info5_2), buff=0.2, color=BLUE, stroke_width=1)
        self.play(Create(sr1))
        info6 = MathTex(r"\text{当}\alpha\text{从0到}2\pi\text{时，}b\text{的轨迹}", font="SimSun", font_size=30, color=BLUE).next_to(info5, DOWN*2).shift(RIGHT*0.8)
        self.play(FadeIn(info6))

        b = Arrow(axes.c2p(0,0), axes.c2p(2,1), buff=0, color=BLUE)
        self.play(Create(b))
        b_label = MathTex(r"b", font="SimSun", font_size=30, color=BLUE).move_to(b.get_end() + 0.2)
        self.play(FadeIn(b_label))

        trace = TracedPath(b.get_end, stroke_width=2, stroke_color=BLUE)
        self.add(trace)
        # 标签也跟着向量一起旋转
        b_label.add_updater(lambda m: m.move_to(b.get_end() + 0.2 * b.get_unit_vector()))
        self.play(Rotate(b, TAU, about_point=axes.c2p(0,0), run_time=1))
        info7 = MathTex(r"\text{比如当}\alpha=120^\circ\text{时}", font="SimSun", font_size=30, color=YELLOW).next_to(info6, DOWN*2, aligned_edge=LEFT)
        self.play(FadeIn(info7))
        self.play(Rotate(b, 2*PI/3, about_point=axes.c2p(0,0), run_time=1))
        arc = Arc(arc_center=axes.c2p(0,0), radius=0.8, start_angle=26.57/180*PI, angle=2*PI/3, color=YELLOW)
        self.bring_to_back(arc)
        self.play(Create(arc))
        arc_label = MathTex(r"\alpha=120^\circ", font="SimSun", font_size=30, color=YELLOW).move_to(axes.c2p(0,1.2))
        self.play(FadeIn(arc_label))
        self.wait(1)

        info8 = MathTex(r"\text{旋转矩阵A是如何来的呢？}", font="SimSun", font_size=30).to_edge(UP)
        self.play(Write(info8))
        self.wait(5)

        self.play(FadeOut(VGroup(axes, info3, info4, info5, info5_1, info5_2, info6, info7, sr1, arc, arc_label, x, x_label, b, b_label, trace, zerolabel)))

        # 推导
        axes2 = Axes(x_range=[-2, 2], y_range=[0, 1], width=8, height=2, axis_config={"stroke_color": GREY, "include_numbers": True, "stroke_width": 2}).shift(UP*1.5)
        zerolabel2 = Text("0", font="SimSun", font_size=26).move_to(axes2.c2p(-0.1,-0.2))
        self.play(FadeIn(axes2), FadeIn(zerolabel2))
        # 旋转θ角度
        dot1 = Dot(axes2.c2p(1,0), color=YELLOW)
        self.play(FadeIn(dot1))
        self.wait(3)
        dot1_arrow = Arrow(axes2.c2p(0,0), axes2.c2p(1,0), buff=0, color=YELLOW)
        trace1 = TracedPath(dot1_arrow.get_end, stroke_width=2, stroke_color=YELLOW)
        self.add(trace1)
        self.play(Rotate(dot1_arrow, PI/6, about_point=axes2.c2p(0,0), run_time=1))
        arc2 = Arc(arc_center=axes2.c2p(0,0), radius=0.4, start_angle=0, angle=PI/6, color=YELLOW)
        self.bring_to_back(arc2)
        self.play(Create(arc2))
        arc2_label = MathTex(r"\theta", font="SimSun", font_size=30, color=YELLOW).move_to(axes2.c2p(0.3,0.06))
        self.play(FadeIn(arc2_label))
        self.wait(3)
        coord1 = MathTex(r"\begin{pmatrix} \cos\theta \\ \sin\theta \end{pmatrix}", font="SimSun", font_size=30, color=YELLOW).move_to(axes2.c2p(1.2,0.6))
        self.play(FadeIn(coord1))
        self.wait(3)
        tip1 = MathTex(r"A\begin{pmatrix} 1 \\ 0 \end{pmatrix}=\begin{pmatrix} \cos\theta \\ \sin\theta \end{pmatrix}", font="SimSun", font_size=30, color=YELLOW).move_to(axes2.c2p(1,-0.5))
        self.play(FadeIn(tip1))
        self.wait(3)

        # 上面基础上再旋转90度
        dot2_arrow = Arrow(axes2.c2p(0,0), axes2.c2p(np.cos(PI/6), np.sin(PI/6)), buff=0, color=BLUE)
        trace2 = TracedPath(dot2_arrow.get_end, stroke_width=2, stroke_color=BLUE)
        self.add(trace2)
        self.play(Rotate(dot2_arrow, PI/2, about_point=axes2.c2p(0,0), run_time=1))
        # 直角符号
        rect = Polygon(axes2.c2p(0,0), axes2.c2p(0,0.1), axes2.c2p(0.1,0.1), axes2.c2p(0.1,0), color=GREY).rotate(PI/6, about_point=axes2.c2p(0,0))
        self.bring_to_back(rect)
        self.play(FadeIn(rect))
        self.wait(1)

        tip2 = MathTex(r"\begin{pmatrix} \cos(\frac{\pi}{2}+\theta) \\ \sin(\frac{\pi}{2}+\theta) \end{pmatrix}=\begin{pmatrix} -\sin\theta \\ \cos\theta \end{pmatrix}", font="SimSun", font_size=30, color=BLUE).move_to(axes2.c2p(-1.45,0.9))
        self.play(FadeIn(tip2))
        self.wait(3)

        dot2 = Dot(axes2.c2p(0,1), color=RED)
        self.play(FadeIn(dot2))
        self.wait(3)
        arc3 = Arc(arc_center=axes2.c2p(0,0), radius=0.4, start_angle=PI/2, angle=PI/6, color=RED)
        self.bring_to_back(arc3)
        self.play(Create(arc3))
        arc3_label = MathTex(r"\theta", font="SimSun", font_size=30, color=RED).move_to(axes2.c2p(-0.05,0.3))
        self.play(FadeIn(arc3_label))
        self.wait(3)
        tip3 = MathTex(r"A\begin{pmatrix} 0 \\ 1 \end{pmatrix}=\begin{pmatrix} -\sin\theta \\ \cos\theta \end{pmatrix}", font="SimSun", font_size=30, color=RED).move_to(axes2.c2p(-1,-0.5))
        self.play(FadeIn(tip3))
        self.wait(3)

        # 综合可得
        tip4 = MathTex(r"A\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}=\begin{pmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{pmatrix}", font="SimSun", font_size=30, color=GREEN).move_to(axes2.c2p(0,-1.2))
        self.play(FadeIn(tip4))
        self.wait(1)
        tip5 = MathTex(r"A=\begin{pmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{pmatrix}", font="SimSun", font_size=30, color=GREEN).move_to(axes2.c2p(0,-1.8))
        self.play(TransformFromCopy(tip4, tip5))
        self.wait(3)
        sr = SurroundingRectangle(tip5, color=GREEN, buff=0.2, stroke_width=1)
        self.play(Create(sr))
        self.wait(3)